# Uses https://github.com/yvesgurcan/deploy-lambda-function

name: Deploy Lambda
on:
  push:
    branches: [ feature/try-catch ]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cat src/requirements.txt | xargs -n 1 python3 -m pip install --user --install-option="--prefix=" --target package/
      - run: cp src/createcandle.py createcandle/sendtweet.py
      - run: cd package/ && zip -r ../package.zip **
      - uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: package.zip
          function-name: volume-candles
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}